### PR TITLE
replace cheshire dependency with clojure.data.json

### PR DESCRIPTION
**Pull request by edenworky**

### CODE REVIEW

**Comment by edenworky** [comment]
Hi! I couldn't get any of the tests to run? It claims to be testing all of the files in the log but finds and runs 0 tests doing so. However this code isn't tested anyway according to the TODOs so hopefully everything works.

**Comment by cloojure** [comment]
Hi - Can you show the error message?  The tests all work for me.  I just upgraded the deps versions and they still work.  Example:

```
~/tupelo > ct
 => time (clojure -X:test)

Running tests in #{"test"}

Testing tst.aaa-bootstrap

--------------------------------------
   Clojure 1.12.0-alpha4    Java 21
--------------------------------------

Testing tst.tupelo.array

Testing tst.tupelo.array.mutable

Testing tst.tupelo.async

Testing tst.tupelo.base64
{:result true, :num-tests 999, :seed 1718982143538, :time-elapsed-ms 64, :test-var "dospec-line-50"}
{:result true, :num-tests 999, :seed 1718982143604, :time-elapsed-ms 46, :test-var "dospec-line-58"}

Testing tst.tupelo.base64url
{:result true, :num-tests 999, :seed 1718982143652, :time-elapsed-ms 35, :test-var "dospec-line-46"}
{:result true, :num-tests 999, :seed 1718982143688, :time-elapsed-ms 29, :test-var "dospec-line-54"}

Testing tst.tupelo.bits

Testing tst.tupelo.chars

Testing tst.tupelo.core

Testing tst.tupelo.core.snip

Testing tst.tupelo.csv

Testing tst.tupelo.demo

Testing tst.tupelo.forest

Testing tst.tupelo.forest-examples

Testing tst.tupelo.hierarchy

Testing tst.tupelo.interval

Testing tst.tupelo.io

Testing tst.tupelo.iuid

Testing tst.tupelo.iuid.prng

Testing tst.tupelo.java-time

Testing tst.tupelo.java-time.convert

Testing tst.tupelo.java-time.epoch

Testing tst.tupelo.lazy

Testing tst.tupelo.lexical

Testing tst.tupelo.math

Testing tst.tupelo.math.modular-arithmetic

Testing tst.tupelo.misc

Testing tst.tupelo.parse

Testing tst.tupelo.parse.tagsoup

Testing tst.tupelo.parse.xml

Testing tst.tupelo.parse.yaml

Testing tst.tupelo.profile

Testing tst.tupelo.schema

Testing tst.tupelo.set

Testing tst.tupelo.spec

Testing tst.tupelo.splat

Testing tst.tupelo.string

Testing tst.tupelo.string.safe

Testing tst.tupelo.tagstr

Testing tst.tupelo.tagval

Testing tst.tupelo.test.jvm

Testing tst.tupelo.types

Testing tst.tupelo.types.coerce

Testing tst.tupelo.uuid

Testing tst.tupelo.vec

Testing tst.tupelo.y64
{:result true, :num-tests 999, :seed 1718982147473, :time-elapsed-ms 65, :test-var "dospec-line-53"}
{:result true, :num-tests 999, :seed 1718982147539, :time-elapsed-ms 47, :test-var "dospec-line-44"}

Ran 427 tests containing 4647 assertions.
0 failures, 0 errors.
  31.98s user 1.72s system 334% cpu 10.065 total
```

**Comment by cloojure** [comment]
Deployed a new version:  [24.06.21-SNAPSHOT](https://clojars.org/tupelo/versions/24.06.21-SNAPSHOT)

**Comment by edenworky** [comment]
Hii sorry I accidentally added a bunch of stuff to the PR, closing and reopening

**Pull request closed without merging**
